name: gh_pages-sitemap-ping
description: "Pinging a sitemap to bing/google search engine"
branding:
  icon: "arrow-up-right"
  color: "orange"

on:
  page_build:
  workflow_dispatch:
  
runs:
  gh_pages-sitemap-ping:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2.4.2

      - name: ping
        env:
          # CUSTOM_URL: ${{ secrets.SITEMAP_URL }} # set custom URL if you use it
          SITEMAP_FILE: "sitemap.xml"
        run: |
          if [ -z "${CUSTOM_URL}" ]; then
            if [ -s "CNAME" ]; then
              MAP_URL="$(cat CNAME)"
            else
              MAP_URL="${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}"
            fi
              MAP_URL="https://${MAP_URL}/${SITEMAP_FILE}"
          else
            MAP_URL="${CUSTOM_URL}"
          fi

          curl -v "http://www.google.com/ping?sitemap=${MAP_URL}" &> /dev/null &
          curl -v "http://www.bing.com/ping?sitemap=${MAP_URL}" &> /dev/null  &
          wait
